### PR TITLE
Cleaned up ANR install process

### LINKED ISSUE #152: Convert subnet-evm E2E tests to use go install
Subnet-evm's e2e tests currently download the network runner multiple times. Let's migrate to using go install so that we don't need to repeat the install process multiple times.

### PR DESCRIPTION
**Pull request by dasconnor**
Use `go install` instead of unpacking a binary.

Closes #152

### CODE REVIEW

**Comment by dasconnor** [comment]
This is blocked on the latest ANR release.

**Comment by ceyonur** [comment]
Does this also close #99 ?

**Comment by dasconnor** [comment]
I don't think this will close #99 because this only addresses the network runner, not avalanchego. One question for you @ceyonur, do you have any idea why the pipeline is failing? Looks like the fee config test. Not sure how/why that could be affected.

**Comment by dasconnor** [comment]
ok, finally passed

**Review by aaronbuchwald — APPROVED** [review]
LGTM

**Review by darioush — APPROVED** [review]

**Pull request merged**
