### PR TITLE
Fixes #464: adding missing import "encoding/json" (used in Stringer-method)

### LINKED ISSUE #464: Missing import of "encoding/json" in precompile-template
**Describe the bug**

The [precompile-template](https://github.com/ava-labs/subnet-evm/blob/master/accounts/abi/bind/precompile_template.go) adds a stringer-method that utilizes `encoding/json`:

File: [accounts/abi/bind/precompile_template.go](https://github.com/ava-labs/subnet-evm/blob/master/accounts/abi/bind/precompile_template.go)

```
// String returns a string representation of the {{.Contract.Type}}Config.
func (c *{{.Contract.Type}}Config) String() string {
	bytes, _ := json.Marshal(c)
	return string(bytes)
}

```
However, `encoding/json` is missed in the imports:

```
import (
	"math/big"
	"errors"
	"fmt"
	"strings"
	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/vmerrs"
	"github.com/ethereum/go-ethereum/common"
)
```

**To Reproduce**
Steps to reproduce the behavior.

1. Generating a precompile according to the tutorial at https://docs.avax.network/subnets/hello-world-precompile-tutorial
2. try to compile the pre-compile and find the missing import

**Expected behavior**

- the compilation of precompiles should compile properly and thus contain all required imports

**Screenshots**

not necessary

**Logs**
If applicable, please include the relevant logs that indicate a problem and/or the log directory of your node. By default, this can be found at `~/.avalanchego/logs/`.

- not necessary

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

- not necessary

**Operating System**

OS ondependent

**Additional context**

### PR DESCRIPTION
**Pull request by itinance**
This PR fixes #464 

- adding missing import-statement "encoding/json"
- re-ordering of imports

## Why this should be merged

it makes the precompile eventually compiling.

## How this works

it adds a missing import-statement

## How this was tested

- create a precompiled contract and compiles the whole repository with it

### CODE REVIEW

**Review by aaronbuchwald — APPROVED** [review]
LGTM - thanks for catching and fixing this! Really appreciate the contribution 🙌

**Review by ceyonur — APPROVED** [review]
LGTM. Thanks!

**Comment by aaronbuchwald** [comment]
@itinance would you mind making sure all commits on this PR are signed? Once they are, this is ready to merge.

**Review by darioush — APPROVED** [review]

**Comment by aaronbuchwald** [comment]
> signed @aaronbuchwald. Anything else?

Nothing left, waiting for CI to pass and then will merge this in. Thanks for your contribution!

**Pull request merged**
